

apiVersion: v1
kind: Service
metadata:
  name: stock-api-service
spec:
  type: NodePort
  selector:
    app: stock-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-service
spec:
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
---
apiVersion: v1
kind: Endpoints
metadata:
  name: rabbit-service
subsets:
  - addresses:
    - ip: "172.17.0.2"
    ports:
    - name: "rabbitmq"
      port: 5672
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: stock-api
spec:
  selector:
    matchLabels:
      app: stock-api
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: stock-api
    spec:
      containers:
        - name: stock-api 
          image: stock-api # Image that will be used to containers in the cluster
          imagePullPolicy: Never
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
          env:
          - name: FINNHUB_API_KEY
            value: "bulktlf48v6prr9i5thg"