
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: stock-api
  namespace: stocks
spec:
  selector:
    matchLabels:
      app: stock-api
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'devweb-app'
        vault.hashicorp.com/agent-inject-secret-finnhub-key.txt: 'secret/data/devwebapp/config'
      namespace: stocks
      labels:
        app: stock-api
    spec:
      serviceAccountName: stock-api-sa
      containers:
        - name: stock-api 
          image: jpdoherty90/stock-api:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
          env:
          - name: RABBIT_HOST
            value: "b-27f17d4d-9343-4389-9f65-436289d2804b.mq.us-east-2.amazonaws.com"
          - name: RABBIT_PORT
            value: "5671"
          - name: RABBIT_USERNAME
            value: "rabbit"
          - name: RABBIT_PASSWORD
            value: "runrabbitrun"
          - name: FINNHUB_API_KEY
            value: "bulktlf48v6prr9i5thg"
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: db-writer
  namespace: stocks
spec:
  selector:
    matchLabels:
      app: db-writer
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      namespace: stocks
      labels:
        app: db-writer
    spec:
      containers:
        - name: db-writer 
          image: jpdoherty90/db-writer:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8081 # The port that the container is running on in the cluster
          env:
          - name: RABBIT_HOST
            value: "b-27f17d4d-9343-4389-9f65-436289d2804b.mq.us-east-2.amazonaws.com"
          - name: RABBIT_PORT
            value: "5671"
          - name: RABBIT_USERNAME
            value: "rabbit"
          - name: RABBIT_PASSWORD
            value: "runrabbitrun"
          - name: DB_URL
            value: "jdbc:mariadb://stocks-db.cdm12ywy2rzy.us-east-2.rds.amazonaws.com:3306/grant_street"
          - name: DB_DRIVER
            value: "org.mariadb.jdbc.Driver"
          - name: DB_USERNAME
            value: "admin"
          - name: DB_PASSWORD
            value: "mariaroot"
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-10-29T18:17:39Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  name: my-service
  namespace: stocks
  resourceVersion: "25233"
  uid: aef90d18-aaca-4de8-8e6e-9ff8a52e8c0b
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.100.196.18
  clusterIPs:
  - 10.100.196.18
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32422
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: stock-api
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: aaef90d18aaca4de88e6e9ff8a52e8c0-676333970.us-east-2.elb.amazonaws.com
---















