---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gs-k8s-demo-2
  region: us-east-1

vpc:
  id: "vpc-5a6f8627"
  securityGroup: "sg-0a91534b28bd50596"
  subnets:
    public:
      public1:
          id: "subnet-4dfd266c"
      public2:
          id: "subnet-75650938"
      public3:
          id: "subnet-02aa735d"

managedNodeGroups:
  - name: managed-ng-4
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
    instanceType: t2.large
    ssh:
      allow: true
      publicKeyName: gs-demo-va
