spring:
  cloud:
    stream:
      default-binder: rabbit
      default:
        group: sender
      bindings:
        stocks:
          destination: stocks-topic
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    ssl:
      enabled: true

finnhub:
  api-key: ${FINNHUB_API_KEY}